#! /bin/sh

sxhkd &
picom -f &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

# polybar

~/.config/polybar/launch.sh --shapes &
~/.config/polybar/shapes/scripts/pywal.sh ~/Pictures/wallpaper &
/usr/bin/ibus-daemon --xim &
xsetroot -cursor_name left_ptr &


# compositing and wallpaper 


#feh --bg-fill   ~/Pictures/wallpaper/minimal.jpg &
xrdb merge ~/.Xresources &  # (terminal theme)

bspc monitor -d I II III IV V VI VII

bspc config border_width         5
bspc config window_gap          6
bsp config presel_feedback_color "#ffffff" 
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a mplayer2 state=floating
#bspc rule -a firefox desktop='^2'
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
#bspc config top_padding 1

# border colors 
bspc config focused_border_color "#fadd00"
bspc config normal_border_color " #144720"
bspc config focus_follows_pointer true


